# command line: main.py recognition -c config/st_gcn/guard/V7/xsub/train.yaml

base_lr: 0.1
batch_size: 64
config: config/st_gcn/guard/V7/xsub/train.yaml
debug: false
device:
- 0
eval_interval: 5
feeder: feeder.feeder.Feeder
ignore_weights: []
log_interval: 100
model: net.st_gcn.Model
model_args:
    dropout: 0.5
    edge_importance_weighting: true
    graph_args:
        layout: openpose
        strategy: spatial
    in_channels: 3
    num_class: 4
nesterov: true
num_epoch: 160
num_worker: 4
optimizer: SGD
pavi_log: false
phase: train
print_log: true
save_interval: 5
save_log: true
save_result: false
show_topk:
- 1
- 5
start_epoch: 0
step:
- 10
- 50
- 90
- 130
test_batch_size: 64
test_feeder_args:
    data_path: ./data/guard/V7/xsub/val_data.npy
    label_path: ./data/guard/V7/xsub/val_label.pkl
train_feeder_args:
    data_path: ./data/guard/V7/xsub/train_data.npy
    label_path: ./data/guard/V7/xsub/train_label.pkl
use_gpu: true
weight_decay: 0.0001
weights: null
work_dir: ./work_dir/guard/V7/xsub
