weights: ./work_dir/recognition/kinetics_skeleton/ST_GCN_400/epoch420_model.pt
model_fps: 30

# model
model: net.st_gcn.Model
model_args:
  in_channels: 3
  num_class: 14
  edge_importance_weighting: True
  graph_args:
    layout: 'openpose'
    strategy: 'spatial'
    
# training
device: [0]
