work_dir: ./work_dir/guard/V7/xviewnobias

# feeder
feeder: feeder.feeder.Feeder
train_feeder_args:
  data_path: ./data/guard/V7/xview/train_data.npy
  label_path: ./data/guard/V7/xview/train_label.pkl
test_feeder_args:
  data_path: ./data/guard/V7/xview/val_data.npy
  label_path: ./data/guard/V7/xview/val_label.pkl

# model
model: net.st_gcn.Model
model_args:
  in_channels: 3
  num_class: 4
  dropout: 0.5
  edge_importance_weighting: True
  graph_args:
    layout: 'openpose'
    strategy: 'spatial'

#optim
weight_decay: 0.0001
base_lr: 0.1
step: [10, 50]

# training
device: [0]
batch_size: 64 
test_batch_size: 64
num_epoch: 80



