weights: ./work_dir/guard/V7/xsub/epoch155_model.pt
model_fps: 30

# model
model: net.st_gcn.Model
model_args:
  in_channels: 3
  num_class: 4
  edge_importance_weighting: True
  graph_args:
    strategy: 'spatial'
    
# training
device: [0]
